### ISSUE TITLE
This is not a "complete" implementation of Optimal Step Nonrigid ICP

### ISSUE THREAD

**Issue by ycjungSubhuman** [Tonsty/Non-Rigid-Registar#1]
In https://github.com/Tonsty/surfaceRegistration , the README says this repository contains a complete implementation of _Optimal Step Nonrigid ICP_ . However, it seems that it has a different implementation than that of the paper. 

* It does not have regularization(i.e. stiffness) easing. (You have to do it yourself)
* There is no landmark term. So 'beta' parameter in compute() is not used

Please be cautious when making use of this code if you need exact implementation of the paper.

**Comment by Tonsty** [comment]
Yes, you're right. I'm sorry for my using the word "complete" inappropriately.
I just want to tell that the implementation is relatively complete compared with those in https://github.com/Tonsty/surfaceRegistration. I'll add the word "relatively" before "complete".

**Comment by ycjungSubhuman** [comment]
@Tonsty I used your code and it has been very helpful for me. I saved a lot of time because of you! This was just a reminder for future users of your code. Thank you for considering my opinion. :)
